<a href="https://colab.research.google.com/github/SKawsar/plotly_dash_examples/blob/main/dash_plotly_examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import plotly.express as px

In [2]:
ecom_sales = pd.read_csv("ecom_sales.csv")

print(ecom_sales.shape)
display(ecom_sales.sample(5))

(500, 6)

,InvoiceNo,Description,OrderValue,Quantity,CustomerID,Country
455,564087,CHILDRENS CUTLERY SPACEBOY,99.60,24,NaN,Hong Kong
152,580771,SET OF 4 NAPKIN CHARMS CROWNS,3.16,4,16015.0,United Kingdom
498,553148,BLUE POLKADOT CUP,27.20,32,NaN,Hong Kong
258,555282,PANTRY WASHING UP BRUSH,17.40,12,12709.0,Germany
208,562035,RETROSPOT TEA SET CERAMIC 11 PC,14.85,3,12627.0,Germany

In [3]:
ecom_sales = ecom_sales.groupby('Country')['OrderValue'].agg('sum')
ecom_sales = ecom_sales.reset_index(name='Total Sales ($)')

print(ecom_sales.shape)
display(ecom_sales.head())

(5, 2)

          Country  Total Sales ($)
0       Australia          6349.89
1          France          2623.79
2         Germany          3153.71
3       Hong Kong          1660.24
4  United Kingdom          3131.01

In [4]:
# Create the bar chart
# Set the DataFrame, x and y
# Set the graph to be horizontal
bar_fig = px.bar(data_frame=ecom_sales, 
                 x='Total Sales ($)', 
                 y='Country',
                 orientation='h', 
                 title='Total Sales by Country')

# Increase the gap between bars
bar_fig.update_layout({'bargap': 0.5})

bar_fig.show()